<?php

/**
 * ffItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class ffItem extends BaseffItem
{
}
