<?php

/**
 * ffLeveChecklistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ffLeveChecklistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ffLeveChecklistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ffLeveChecklist');
    }
}