<?php

/**
 * sfGuardRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ffxiv
 * @subpackage model
 * @author     your_name_goes_here
 * @version    SVN: $Id$
 */
class sfGuardRememberKey extends PluginsfGuardRememberKey
{
}
