ffClass:
  options:
    orderBy:                 position ASC
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    name:
      type:                  enum
      values:                ['alchemist', 'archer', 'armorer', 'blacksmith', 'botanist', 'carpenter', 'conjurer', 'culinarian', 'fisher', 'gladiator', 'goldsmith', 'lancer', 'leatherworker', 'marauder', 'miner', 'pugilist', 'thaumaturge', 'weaver']
      notnull:               true
    abbreviation:
      type:                  string(255)
    position:                integer(4)

ffItem:
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    name:                    string(255)
    type:
      type:                  enum
      values:                ['armor', 'weapon', 'tool', 'food', 'potion', 'ingredient', 'training', 'currency']
      notnull:               false

ffLeve:
  options:
    orderBy:                 name ASC
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
#    product_id:
#      type:                  integer(4)
#      notnull:               true
    name:                    string(255)
    type:
      type:                  enum
      values:                ['local','regional']
    poc:
      type:                  string(255)
    description:             string(1023)
    objectives:              string(1023)
    reward:                  string(1023)
    issuing_authority:       string(255)
    duration:                string(255)
    recommended_classes:     string(255)
    levequest_location:      string(255)
    favor_required:          integer(4)
    deliver_to:              string(255)
  actAs:
    Timestampable:
    Sluggable:
#  relations:
#    Product:
#      type:                  one
#      foreignType:           many
#      class:                 myProduct
#      foreignAlias:          ProductImages
#      local:                 product_id
#      onDelete:              cascade

ffServer:
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    name:
      type:                  enum
      values:                ['Besaid', 'Bodhum', 'Cornelia', 'Fatul', 'Figaro', 'Gysahl', 'Istory', 'Karnak', 'Kashuan', 'Lindblum', 'Melmond', 'Mysidia', 'Palamecia', 'Rabanastre', 'Saronia', 'Selbina', 'Trabia', 'Wutai']
      notnull:               false




#ffChecklistLeve:
#  options:
#    orderBy:                 position ASC
#  columns:
#    id:
#      type:                  integer(4)
#      primary:               true
#      autoincrement:         true
#    user_id:
#      type:                  integer(4)
#      notnull:               true
#    position:                integer(4)
#    visited:                 boolean
#  actAs:
#    Timestampable:
#  relations:
#    Product:
#      type:                  one
#      foreignType:           many
#      class:                 ffUser
#      foreignAlias:          ChecklistLeves
#      local:                 user_id
#      onDelete:              cascade


