ffClass:
  options:
    orderBy:                 position ASC
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    name:
      type:                  enum
      values:                ['alchemist', 'archer', 'armorer', 'blacksmith', 'botanist', 'carpenter', 'conjurer', 'culinarian', 'fisher', 'gladiator', 'goldsmith', 'lancer', 'leatherworker', 'marauder', 'miner', 'pugilist', 'thaumaturge', 'weaver']
      notnull:               true
    abbreviation:
      type:                  string(255)
    position:                integer(4)

ffItem:
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    name:                    string(255)
    type:
      type:                  enum
      values:                ['armor', 'weapon', 'tool', 'food', 'potion', 'ingredient', 'training', 'currency']
      notnull:               false

ffLeve:
  options:
    orderBy:                 name ASC
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
#    product_id:
#      type:                  integer(4)
#      notnull:               true
    name:                    string(255)
    type:
      type:                  enum
      values:                ['local','regional']
    poc:
      type:                  string(255)
    description:             string(1023)
    objectives:              string(1023)
    reward:                  string(1023)
    issuing_authority:       string(255)
    duration:                string(255)
    recommended_classes:     string(255)
    levequest_location:      string(255)
    favor_required:          integer(4)
    deliver_to:              string(255)
  actAs:
    Timestampable:
    Sluggable:
  relations:
    CheckedBy:
      type:                  one
      foreignType:           many
      class:                 ffLeveChecklist
      foreignAlias:          ffLeve2LeveChecklist
      local:                 id
      onDelete:              cascade

ffLeveChecklist:
#  inheritance:
#    type:                    concrete
#    extends:                 ffLeve
  options:
    orderBy:                 position ASC
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    leve_id:
      type:                  integer(4)
      notnull:               true
    user_id:
      type:                  integer(4)
      notnull:               true
    position:                integer(4)
    is_visited:              boolean
  indexes:
    leve_user_idx:
      fields:                [leve_id, user_id]
      primary:               true
  actAs:
    Timestampable:
  relations:
    ffLeves:
      type:                  many
      foreignType:           one
      class:                 ffLeve
      local:                 leve_id
      foreign:               id
      foreignAlias:          ffLeve2ffLeveChecklist
    Users:
      type:                  many
      foreignType:           one
      class:                 sfGuardUser
      local:                 user_id
      foreign:               id
      foreignAlias:          sfGuardUser2LeveChecklist





ffServer:
  columns:
    id:
      type:                  integer(4)
      primary:               true
      autoincrement:         true
    name:
      type:                  enum
      values:                ['Besaid', 'Bodhum', 'Cornelia', 'Fatul', 'Figaro', 'Gysahl', 'Istory', 'Karnak', 'Kashuan', 'Lindblum', 'Melmond', 'Mysidia', 'Palamecia', 'Rabanastre', 'Saronia', 'Selbina', 'Trabia', 'Wutai']
      notnull:               false


